version: "3"

services:
    app:
        container_name: dteservice_app
        build:
            context: .
            dockerfile: Dockerfile
            target: builder
        command: sh -c "npm run m:run && npm run seed:run && npm run start:dev"
        ports:
            - 3000:3000
        volumes:
            - .:/usr/app
            - /usr/app/node_modules
        environment:
            - PORT=3000
            - NODE_ENV=DEV
            - POSTGRES_HOST=postgres_db
            - POSTGRES_PORT=5432
            - POSTGRES_USER=dteservice
            - POSTGRES_PASSWORD=dteservice
            - POSTGRES_DB=dteservice
            - JWT_PRIVATE_KEY=dRm7KQSPvFVj4mx/xopOvo7zpZIwqYEx8l/CFNoBFn0=
            - BCRYPT_SALT_OR_ROUNDS=12
        links:
            - postgres_db
        depends_on:
            - postgres_db
    postgres_db:
        container_name: dteservice_postgres_db
        image: postgres:13-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=dteservice
            - POSTGRES_PASSWORD=dteservice
            - POSTGRES_DB=dteservice
        volumes:
            - pgdata:/data/postgres

volumes:
    pgdata:
        driver: local
